/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as PortalTokenRouteImport } from './routes/portal.$token'
import { Route as AuthenticatedOrcamentosRouteImport } from './routes/_authenticated/orcamentos'
import { Route as AuthenticatedFaturamentoRouteImport } from './routes/_authenticated/faturamento'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedEquipeRastrearRouteImport } from './routes/_authenticated/equipe.rastrear'
import { Route as AuthenticatedAgendaJobIdRouteImport } from './routes/_authenticated/agenda.$jobId'

const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrcamentosRoute = AuthenticatedOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFaturamentoRoute =
  AuthenticatedFaturamentoRouteImport.update({
    id: '/faturamento',
    path: '/faturamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRastrearRoute =
  AuthenticatedEquipeRastrearRouteImport.update({
    id: '/rastrear',
    path: '/rastrear',
    getParentRoute: () => AuthenticatedEquipeRoute,
  } as any)
const AuthenticatedAgendaJobIdRoute =
  AuthenticatedAgendaJobIdRouteImport.update({
    id: '/$jobId',
    path: '/$jobId',
    getParentRoute: () => AuthenticatedAgendaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/dispatch': typeof DispatchRoute
  '/agenda': typeof AuthenticatedAgendaRouteWithChildren
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/equipe': typeof AuthenticatedEquipeRouteWithChildren
  '/faturamento': typeof AuthenticatedFaturamentoRoute
  '/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/portal/$token': typeof PortalTokenRoute
  '/agenda/$jobId': typeof AuthenticatedAgendaJobIdRoute
  '/equipe/rastrear': typeof AuthenticatedEquipeRastrearRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/dispatch': typeof DispatchRoute
  '/agenda': typeof AuthenticatedAgendaRouteWithChildren
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/equipe': typeof AuthenticatedEquipeRouteWithChildren
  '/faturamento': typeof AuthenticatedFaturamentoRoute
  '/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/portal/$token': typeof PortalTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/agenda/$jobId': typeof AuthenticatedAgendaJobIdRoute
  '/equipe/rastrear': typeof AuthenticatedEquipeRastrearRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/dispatch': typeof DispatchRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRouteWithChildren
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRouteWithChildren
  '/_authenticated/faturamento': typeof AuthenticatedFaturamentoRoute
  '/_authenticated/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/portal/$token': typeof PortalTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/agenda/$jobId': typeof AuthenticatedAgendaJobIdRoute
  '/_authenticated/equipe/rastrear': typeof AuthenticatedEquipeRastrearRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dispatch'
    | '/agenda'
    | '/clientes'
    | '/configuracoes'
    | '/equipe'
    | '/faturamento'
    | '/orcamentos'
    | '/portal/$token'
    | '/agenda/$jobId'
    | '/equipe/rastrear'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/dispatch'
    | '/agenda'
    | '/clientes'
    | '/configuracoes'
    | '/equipe'
    | '/faturamento'
    | '/orcamentos'
    | '/portal/$token'
    | '/'
    | '/agenda/$jobId'
    | '/equipe/rastrear'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/dispatch'
    | '/_authenticated/agenda'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/equipe'
    | '/_authenticated/faturamento'
    | '/_authenticated/orcamentos'
    | '/portal/$token'
    | '/_authenticated/'
    | '/_authenticated/agenda/$jobId'
    | '/_authenticated/equipe/rastrear'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DispatchRoute: typeof DispatchRoute
  PortalTokenRoute: typeof PortalTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orcamentos': {
      id: '/_authenticated/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof AuthenticatedOrcamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faturamento': {
      id: '/_authenticated/faturamento'
      path: '/faturamento'
      fullPath: '/faturamento'
      preLoaderRoute: typeof AuthenticatedFaturamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe/rastrear': {
      id: '/_authenticated/equipe/rastrear'
      path: '/rastrear'
      fullPath: '/equipe/rastrear'
      preLoaderRoute: typeof AuthenticatedEquipeRastrearRouteImport
      parentRoute: typeof AuthenticatedEquipeRoute
    }
    '/_authenticated/agenda/$jobId': {
      id: '/_authenticated/agenda/$jobId'
      path: '/$jobId'
      fullPath: '/agenda/$jobId'
      preLoaderRoute: typeof AuthenticatedAgendaJobIdRouteImport
      parentRoute: typeof AuthenticatedAgendaRoute
    }
  }
}

interface AuthenticatedAgendaRouteChildren {
  AuthenticatedAgendaJobIdRoute: typeof AuthenticatedAgendaJobIdRoute
}

const AuthenticatedAgendaRouteChildren: AuthenticatedAgendaRouteChildren = {
  AuthenticatedAgendaJobIdRoute: AuthenticatedAgendaJobIdRoute,
}

const AuthenticatedAgendaRouteWithChildren =
  AuthenticatedAgendaRoute._addFileChildren(AuthenticatedAgendaRouteChildren)

interface AuthenticatedEquipeRouteChildren {
  AuthenticatedEquipeRastrearRoute: typeof AuthenticatedEquipeRastrearRoute
}

const AuthenticatedEquipeRouteChildren: AuthenticatedEquipeRouteChildren = {
  AuthenticatedEquipeRastrearRoute: AuthenticatedEquipeRastrearRoute,
}

const AuthenticatedEquipeRouteWithChildren =
  AuthenticatedEquipeRoute._addFileChildren(AuthenticatedEquipeRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRouteWithChildren
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRouteWithChildren
  AuthenticatedFaturamentoRoute: typeof AuthenticatedFaturamentoRoute
  AuthenticatedOrcamentosRoute: typeof AuthenticatedOrcamentosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRouteWithChildren,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRouteWithChildren,
  AuthenticatedFaturamentoRoute: AuthenticatedFaturamentoRoute,
  AuthenticatedOrcamentosRoute: AuthenticatedOrcamentosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DispatchRoute: DispatchRoute,
  PortalTokenRoute: PortalTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
